import { SchemaScript, generateBreadcrumbSchema } from "../../lib/schema";
import Link from "next/link";
import Navbar from "../../components/Navbar";

export const metadata = { 
  title: "Editorial Policy | KaroTools", 
  description: "Read the editorial and fact-checking policy of KaroTools. We prioritize accuracy and official sources.", 
  alternates: { canonical: "https://karotools.in/editorial-policy" }  
};

export default function EditorialPolicyPage() {
  return (
    <div className="min-h-screen bg-[var(--bg-primary)] text-[var(--text-primary)] font-['DM_Sans']">
      <Navbar />
      <div className="max-w-4xl mx-auto px-6 py-20">
        <h1 className="text-4xl md:text-5xl font-extrabold font-['Plus_Jakarta_Sans'] mb-6 bg-clip-text text-transparent bg-gradient-to-r from-white to-[#818cf8] text-center">
          Editorial Policy
        </h1>
        <div className="glass-panel p-8 md:p-12 rounded-3xl border border-[var(--glass-border)] bg-[var(--glass-bg)] mt-12 space-y-8">
          <section>
            <h2 className="text-2xl font-bold font-['Plus_Jakarta_Sans'] mb-4 text-[#38bdf8]">1. Source-First Content</h2>
            <p className="text-[var(--text-secondary)] leading-relaxed">
              Every calculator, guide, and blog post on KaroTools is built with a "source-first" approach. We do not invent rules or interpret grey areas of the law. We strictly rely on explicit guidelines published by the Income Tax Department, GST Portal, and CBIC.
            </p>
          </section>
          <section>
            <h2 className="text-2xl font-bold font-['Plus_Jakarta_Sans'] mb-4 text-[#38bdf8]">2. Fact-Checking Process</h2>
            <p className="text-[var(--text-secondary)] leading-relaxed">
              Before a new tool is published, it undergoes internal testing against real-world scenarios and official government tax calculators (where available). While we do not have external Chartered Accountants reviewing every page, our internal maintainers rigorously verify the math.
            </p>
          </section>
          <section>
            <h2 className="text-2xl font-bold font-['Plus_Jakarta_Sans'] mb-4 text-[#38bdf8]">3. Updates and Corrections</h2>
            <p className="text-[var(--text-secondary)] leading-relaxed">
              We update our content annually (after the Union Budget) and periodically as new GST notifications arise. If an error is found, we issue a correction immediately. You can report errors to <a href="mailto:daxpatel093@gmail.com" className="text-[#38bdf8] hover:underline">daxpatel093@gmail.com</a>.
            </p>
          </section>
          <section>
            <h2 className="text-2xl font-bold font-['Plus_Jakarta_Sans'] mb-4 text-[#38bdf8]">4. AI Assistance Policy</h2>
            <p className="text-[var(--text-secondary)] leading-relaxed">
              We may use AI tools to help write code, format text, or check spelling. However, <strong>no financial advice, tax rule, or legal claim is generated by AI</strong> without strict human verification against an official source.
            </p>
          </section>
          <section>
            <h2 className="text-2xl font-bold font-['Plus_Jakarta_Sans'] mb-4 text-[#38bdf8]">5. No Fake Financial Advice</h2>
            <p className="text-[var(--text-secondary)] leading-relaxed">
              We do not provide personalized financial advice, and we do not claim to. Please read our <Link href="/disclaimer" className="text-[#38bdf8] hover:underline">Full Disclaimer</Link> for more information.
            </p>
          </section>
        </div>
      </div>
      <SchemaScript schema={generateBreadcrumbSchema([{name: "Home", url: "https://karotools.in"}, {name: "Editorial Policy", url: "https://karotools.in/editorial-policy"}])} />
    </div>
  );
}
