import { SchemaScript, generateBreadcrumbSchema } from "../../lib/schema";
import TrustPageLayout, { TrustSectionCard } from "../../components/TrustPageLayout";
import Link from "next/link";
import { BookOpen, CheckCircle, RefreshCw, Cpu, ShieldAlert } from "lucide-react";

export const metadata = { 
  title: "Editorial Policy | KaroTools", 
  description: "Read the editorial and fact-checking policy of KaroTools. We prioritize accuracy and official sources.", 
  alternates: { canonical: "https://karotools.in/editorial-policy" }  
};

export default function EditorialPolicyPage() {
  return (
    <>
      <TrustPageLayout
        title="Editorial Policy"
        subtitle="Our commitment to accuracy, unbiased information, and strict adherence to official sources."
        lastUpdated="February 2026"
      >
        <TrustSectionCard title="1. Source-First Content" icon={BookOpen}>
          <p>
            Every calculator, guide, and blog post on KaroTools is built with a "source-first" approach. We do not invent rules or interpret grey areas of the law. We strictly rely on explicit guidelines published by the Income Tax Department, GST Portal, and CBIC.
          </p>
        </TrustSectionCard>

        <TrustSectionCard title="2. Fact-Checking Process" icon={CheckCircle}>
          <p>
            Before a new tool is published, it undergoes internal testing against real-world scenarios and official government tax calculators (where available). While we do not have external Chartered Accountants reviewing every page, our internal maintainers rigorously verify the math.
          </p>
        </TrustSectionCard>

        <TrustSectionCard title="3. Updates and Corrections" icon={RefreshCw}>
          <p>
            We update our content annually (after the Union Budget) and periodically as new GST notifications arise. If an error is found, we issue a correction immediately. You can report errors to <a href="mailto:daxpatel093@gmail.com" className="text-[#38bdf8] hover:underline">daxpatel093@gmail.com</a>.
          </p>
        </TrustSectionCard>

        <TrustSectionCard title="4. AI Assistance Policy" icon={Cpu}>
          <p>
            We may use AI tools to help write code, format text, or check spelling. However, <strong>no financial advice, tax rule, or legal claim is generated by AI</strong> without strict human verification against an official source.
          </p>
        </TrustSectionCard>

        <TrustSectionCard title="5. No Fake Financial Advice" icon={ShieldAlert}>
          <p>
            We do not provide personalized financial advice, and we do not claim to. Please read our <Link href="/disclaimer" className="text-[#38bdf8] hover:underline">Full Disclaimer</Link> for more information.
          </p>
        </TrustSectionCard>
      </TrustPageLayout>
      <SchemaScript schema={generateBreadcrumbSchema([{name: "Home", url: "https://karotools.in"}, {name: "Editorial Policy", url: "https://karotools.in/editorial-policy"}])} />
    </>
  );
}
